apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/creatorId: user-w8l82
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.0.35"],"port":32453,"protocol":"TCP","serviceName":"default:code-test-nodeport","allNodes":true}]'
  creationTimestamp: "2019-06-18T01:26:39Z"
  generation: 13
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-code-test
  name: code-test
  namespace: default
  resourceVersion: "16416"
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/code-test
  uid: 1ec4503a-9168-11e9-ae16-000c290a024a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-code-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-06-18T04:29:02Z"
        field.cattle.io/ports: '[[{"containerPort":1234,"dnsName":"code-test-nodeport","kind":"NodePort","name":"1234tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-code-test
    spec:
      containers:
      - image: 192.168.0.34:5000/generator
        imagePullPolicy: Always
        name: code-test
        ports:
        - containerPort: 1234
          name: 1234tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-18T01:38:21Z"
    lastUpdateTime: "2019-06-18T01:38:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-06-18T04:28:48Z"
    lastUpdateTime: "2019-06-18T04:29:08Z"
    message: ReplicaSet "code-test-79ffc46cdf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 13
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
